### ISSUE TITLE
Could you describe your current Hotspotter workflow?

### ISSUE THREAD

**Issue by swyngaard** [polar-computing/3DSeals#2]
Hi All,

I'm currently installing Hotspotter for development.

Could you describe your workflow (with as much detail as you think is relevant) so I can replicate your process on my side? Screenshots will help too.

**Comment by aborowicz** [comment]
Hi Sam,

I was working with the GUI version. Not sure if there's a command line-only version.  

File->New database
File->Import images (Here I started with one image, then added another, and then another, building the catalog by running each image against the others. If there was no match, it stayed in.)
At this I basically had to cycle through each image, creating a bounding box for the seal by selecting two points. Under the "Actions" tab, you can create a new "chip" that is unique to the seal. Then onto the next seal. If there's a faster way to do this, I didn't find it. Some sort of pre-process step that locates the seal would be awesome there.

Once every image has a chip, I go to the "Chip Table" tab, select the first chip, and hit Q (or alternatively select "query" from the action menu. It should run the chip through the catalog of chips and return a score for all the possible matches from best to worst.

Sorry I can't really provide screenshots. I'm working remotely this week and it takes about 10 seconds to get a click to register on my desktop in the lab. 

By adding images one by one, creating a chip, and running the chip against the catalog, I get to view all of the scored possible matches for each new image and visually evaluate whether it's correct or not. Occasionally this process would miss the match all together and return the true match buried in the weeds somewhere with a score at or near zero. Sometimes it would score non-matches much higher than the real match.
